# Generated by Django 4.1.1 on 2022-12-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_odoouser_delete_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odoouser',
            name='odoo_id',
        ),
        migrations.RemoveField(
            model_name='odoouser',
            name='user',
        ),
        migrations.AddField(
            model_name='odoouser',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
