# Generated by Django 4.1.1 on 2022-12-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_odoouser_odoo_id_remove_odoouser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoouser',
            name='db',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='odoouser',
            name='url',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
